# image will be published to ghcr.io/<user>/<name>
name: fearlixOS
# description will be included in the image's metadata
description: Fedora Silverblue by Fearlix SRL

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
      - btrfs-assistant
      - neovim
      - alacritty
      - vorta
      # gnome extensions
      - gnome-shell-extension-pop-shell
      - xprop
      - gnome-shell-extension-gsconnect
      - nautilus-gsconnect
      - webextension-gsconnect
      # virtualization
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - libguestfs-tools
      - python3-libguestfs
      - podman-compose
    remove:
      - gnome-extensions-app

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Caffeine
      - Color Picker
      - Forge
      - User Themes
      - 307 # dash-to-dock

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraMono

  - type: yafti

  - type: systemd
    user:
      disabled:
        - livepaper.service

  - type: script
    scripts:
      - livepaper.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
